[TAN-862] Upgrade to Ruby 3.2.3
- We updgraded GraphQL to v1.12.24. v1.11.10 was causing the following error:

    TypeError: Refinement#include has been removed (TypeError)

            include Methods
                    ^^^^^^^
    /cl2_back/vendor/bundle/ruby/3.2.0/gems/graphql-1.11.10/lib/graphql/deprecated_dsl.rb:38:in `include'

- We added back the `:exists?` alias to `File#exist?` to make the `rspec_api_documentation` gem happy. Otherwise, it would raise the following error:

    /cl2_back/vendor/bundle/ruby/3.2.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/writers/writer.rb:17:in `clear_docs': undefined method `exists?' for File:Class (NoMethodError)

            if File.exists?(docs_dir)
                   ^^^^^^^^