[TAN-862] Upgrade to Ruby 3.2.3
We updgraded GraphQL to v1.12.24. v1.11.10 was causing the following error:
    TypeError: Refinement#include has been removed (TypeError)

            include Methods
                    ^^^^^^^
    /cl2_back/vendor/bundle/ruby/3.2.0/gems/graphql-1.11.10/lib/graphql/deprecated_dsl.rb:38:in `include'