fix migration: wrong table names
This caused:
ArgumentError: Index name 'index_project_folders_project_folder_images_on_project_folder_id' on table 'project_folders_project_folder_images' is too long; the limit is 63 characters