[TAN-3358] Upgrade Ruby to version 3.3.4
Upgrade Ruby to resolve the following bug encountered when upgrading Rails to version 7.1.5.1:
```
ArgumentError: comparison of String with nil failed (ArgumentError)
    msg = " #{RUBY_VERSION < SINCE[gem] ? "will no longer be" : "is not"} part of the default gems since Ruby #{SINCE[gem]}."
```

Refer to https://bugs.ruby-lang.org/issues/20450 for more details.