[CL-2052] Handle nil omniauth.params
Not sure why, but sometimes request.env['omniauth.params'] is nil
https://sentry.hq.citizenlab.co/organizations/citizenlab/issues/68343/?project=2&query=is%3Aunresolved

and so it raised

NoMethodError OmniauthCallbackController#failure
undefined method `with_indifferent_access' for nil:NilClass

app/controllers/omniauth_callback_controller.rb in failure_redirect at line 125
app/controllers/omniauth_callback_controller.rb in failure at line 23