[CL-2216] Fix tests failing with CSS.supports is not a function
This CSS.supports check is used only for IE, which is not supported
anymore.

The error was:
in Image (created by TwoColumnLayout__HeaderImage)
detail: TypeError: CSS.supports is not a function
  at Image.supports [as render] (/home/main/projects/cl/citizenlab/front/app/components/UI/Image/index.tsx:121:41)

It could be reproduced by running:
npm test app/containers/CustomPageShow/CustomPageHeader/CustomPageHeader.test.tsx