[No ticket] Fix seeds
```
NoMethodError:
  undefined method `configure_timeline_for' for #<MultiTenancy::Seeds::Projects:0x00005622c812db80>
./engines/ee/multi_tenancy/db/seeds/projects.rb:51:in `block in run'
./engines/ee/multi_tenancy/db/seeds/projects.rb:9:in `times'
./engines/ee/multi_tenancy/db/seeds/projects.rb:9:in `run'
./engines/ee/multi_tenancy/db/seeds/runner.rb:109:in `seed_localhost_tenant'
./engines/ee/multi_tenancy/db/seeds/runner.rb:81:in `execute'
./engines/ee/multi_tenancy/db/seeds/runner.rb:230:in `<top (required)>'
/usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
./db/seeds.rb:4:in `<top (required)>'
/usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
./engines/ee/multi_tenancy/spec/db/seedfile_spec.rb:15:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/ros-apartment-2.11.0/lib/apartment/adapters/abstract_adapter.rb:89:in `switch'
./engines/ee/multi_tenancy/spec/db/seedfile_spec.rb:14:in `block (2 levels) in <top (required)>'
./spec/spec_helper.rb:172:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```