[CL-3635] Replace usage of [] with fetch to improve error message
The previous error message "NoMethodError: undefined method `each' for nil:NilClass" was not informative. By replacing the usage of [] with fetch, we now get the value of the missing key.