[TAN-4119] Fix Oostende verification method
There is no `:custom_field_key` in the config, so the `locked_custom_fields` method returns `nil`, which  causes a `NoMethodError` (undefined method `to_sym` for `nil`).