[NO-TICKET] Fix e2e circleci job
Upgrade the lastpass client to solve the following error:
> Error: Unable to fetch blob. Either your session is invalid and you need to login with `lpass login`, you need to synchronize, your blob is empty, or there is something wrong with your internet connection.

(None of the reasons mentioned in the error message were the cause of the error.)